apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: order-management-api-hpa
  namespace: easy-shopping
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: order-management-api-deployment
  minReplicas: 1
  maxReplicas: 5
  targetCPUUtilizationPercentage: 70
