apiVersion: v1
kind: Service
metadata:
  name: order-management-api-service
  namespace: order-management
spec:
  type: LoadBalancer
  selector:
    app: order-management-api
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
      name: http
