name: Show Me the S3cr3tz
on: [push]

jobs:
  debug:
    name: Debug
    runs-on: ubuntu-latest

    steps:
    - name: Check out code
      uses: actions/checkout@v2

    - name: Set up secret file
      env:
        AKS_CTSECLUSTER_KUBECONFIG: ${{ secrets.AKS_CTSECLUSTER_KUBECONFIG }}
        KUBE_CONFIG: ${{ secrets.KUBE_CONFIG }}
      run: |
        echo $AKS_CTSECLUSTER_KUBECONFIG >> secrets.txt
        echo $KUBE_CONFIG >> secrets.txt

    - name: Run tmate
      uses: mxschmitt/action-tmate@v2
